apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongo-node-app
  name: mongo-node-app
  namespace: _{_NAMESPACE_}_
spec:
  replicas: _{_REPLICAS_}_
  selector:
    matchLabels:
      app: mongo-node-app
  strategy: {}
  template:
    metadata:
      labels:
        app: mongo-node-app
    spec:
      containers:
      - image: _{_IMAGE_}_
        imagePullPolicy: Always
        name: mongo-node-app
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        envFrom:
        - secretRef:
            name: mongo-db-creds