apiVersion: v1
kind: Secret
metadata:
  name: mongo-db-creds
  namespace: development
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://marviigrey:marviigrey18$@mycluster.ybh2ayz.mongodb.net/?retryWrites=true&w=majority&appName=myCluster"
  MONGO_USERNAME: "marviigrey"
  MONGO_PASSWORD: "marviigrey18"
